/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'CountWalkCode' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f10x.h"

/* Keil::CMSIS Driver:I2C@2.2 */
#define RTE_Drivers_I2C1                /* Driver I2C1 */
#define RTE_Drivers_I2C2                /* Driver I2C2 */


#endif /* RTE_COMPONENTS_H */
